# Generated by Django 3.2.6 on 2021-08-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rollnumber', models.CharField(max_length=200, unique=True)),
                ('dateofbirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=100)),
                ('rollnumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='japi.students')),
            ],
        ),
    ]
